### ISSUE TITLE
Renumber has a bug

### ISSUE THREAD

**Issue by anthousis** [lemire/StablePriorityQueue.js#2]
Initial code at line 56
`buffer.push(this.poll().value);`
Fixed
`buffer.push(this.poll());`

**Comment by lemire** [comment]
Do you have a failing test so we can verify that there is a bug?

**Comment by anthousis** [comment]
Check the return of poll method.
I left my office now

**Comment by lemire** [comment]
Our tests do pass, as you can verify:

https://travis-ci.org/lemire/StablePriorityQueue.js

There might be a bug, but we do systematically test the values returned by the poll method, using unit tests.

Can you please provide a failing test?

I am going to close this issue, reopen once you have a failing test.

**Comment by anthousis** [comment]
I think that the problem is that the function renumber is not in any of your union tests.
Below is the simplest example. Insert 10 int values, call renumber and try to print out the elements.

```
const spq = require('stablepriorityqueue');
let queue = new spq(function(a,b) {
        return b - a;
});

for (var i = 0; i < 10; ++i) {
        queue.add(i);
}

queue.renumber();

while (!queue.isEmpty()) {
        console.log(queue.poll());
}
```

result is 

```
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
```
