### ISSUE TITLE
Bug in method renumber

### ISSUE THREAD

**Issue by anthousis** [lemire/StablePriorityQueue.js#3]
The bug is at line 56 where method **renumber** code tries to access the .value of the returned element.
**poll** method returns the .value of the stored element and thus after calling method **renumber** all elements have been lost (undefined).

Initial code at line 56
buffer.push(this.poll().value);
Fix
buffer.push(this.poll());

Below is the simplest example. Insert 10 int values, call renumber and try to print out the elements.

```
const spq = require('stablepriorityqueue');
let queue = new spq(function(a,b) {
        return b - a;
});

for (var i = 0; i < 10; ++i) {
        queue.add(i);
}

queue.renumber();

while (!queue.isEmpty()) {
        console.log(queue.poll());
}
```
result is
```
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
undefined
```

**Comment by lemire** [comment]
Why would you call renumber in this manner? The function renumber is called automatically as needed by the add method. You are not supposed to call it yourself as a end-user.

That's not a valid use case here. If you want to demonstrate a bug, you have to do so by just calling the valid methods such as poll, isEmpty, add.

**Comment by anthousis** [comment]
I have a case where the weight of the stored elements is updated. Not for 1
but for n items. Instead of removing and re-adding n items its more fitting
to reorder them.

If you think that this is not an issue, then leave it as it is.

If I am not mistaken (not in front of my PC at the moment) the function is
not declared as internal.

Best,
Anthousis

**Comment by lemire** [comment]
> I have a case where the weight of the stored elements is updated. Not for 1 but for n items. Instead of removing and re-adding n items its more fitting to reorder them.

The renumber function removes all elements and adds them back. There is surely a way to speed up the use case you describe, but the renumber function will not be particularly faster. 

I invite a pull request providing an optimized function.

> If I am not mistaken (not in front of my PC at the moment) the function is
not declared as internal.

Indeed. You are correct, but it is not documented as something an end-user should care about.

**Comment by lemire** [comment]
And I have added the following test...

```javascript
    var queue = new StablePriorityQueue(function(a, b) {
      return b - a;
    });
    for (var i = 0; i < 10; ++i) {
      queue.add(i);
    }
    queue.renumber();
    var counter = 9;
    while (!queue.isEmpty()) {
      if(queue.poll() != counter) throw "bug";
      counter--;
    }
```

I don't think it makes sense, but you should be able to use it that way if you want to.

I have issued a new release.

**Comment by anthousis** [comment]
Thanks.
